name: temple_run_2d
description: A 2D endless runner game similar to Temple Run.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flame: ^1.28.1
  provider: ^6.1.5
  shared_preferences: ^2.5.3
  firebase_core: ^3.13.0
  cloud_firestore: ^5.6.7
  uuid: ^4.5.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.2

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/images/characters/
    - assets/images/obstacles/
    - assets/images/collectibles/
    - assets/images/background/
    - assets/images/player/
